---
- name: Setup dan's environment
  hosts: localhost
  gather_facts: no
  vars:
    user_name: "dan"
    home_dir: "/Users/{{ user_name }}"
    nvim_dir: "{{ home_dir }}/.config/nvim"
    fish_dir: "{{ home_dir }}/.config/fish"

  tasks:

    - name: Install brew packages
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ (lookup('file', 'packages_common.yml') | from_yaml)['packages'] }}"

    - name: Install cask packages
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ (lookup('file', 'packages_common.yml') | from_yaml)['casks'] }}"

    - name: Clone neovim config
      git:
        repo: https://github.com/dme86/neovim
        dest: "{{ nvim_dir }}"
        clone: yes
        update: yes
        force: yes
        depth: 1
      become_user: "{{ user_name }}"

    - name: Clone fish config
      git:
        repo: https://github.com/dme86/fish
        dest: "{{ fish_dir }}"
        clone: yes
        update: yes
        force: yes
        depth: 1
      become_user: "{{ user_name }}"
